name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 25.1
          - 25.3
          - 26.1
          - 26.3
          - 27.1
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        curl -s --remote-name-all https://raw.githubusercontent.com/eschulte/emacs-web-server/master/web-server{,-status-codes}.el
        emacs -Q --batch -L . -f batch-byte-compile web-server*
    - name: Byte Compile
      run: emacs -Q --batch -L . --eval "(setq byte-compile-error-on-warn t)" -f batch-byte-compile edit-buffers-remotely.el
    - name: Run Tests
      run: emacs -Q --batch -L . -l edit-buffers-remotely-tests -f ert-run-tests-batch-and-exit
